import { DeleteObjectCommand, ListObjectsV2Command, S3Client } from '@aws-sdk/client-s3'
import { NextResponse } from 'next/server'
import { createHmac, timingSafeEqual } from 'crypto'
const client=new S3Client({region:'auto',endpoint:`https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,credentials:{accessKeyId:process.env.R2_ACCESS_KEY_ID!,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY!}})
const imageExtensions:Record<string,string>={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',avif:'image/avif',heic:'image/heic',heif:'image/heif',bmp:'image/bmp',svg:'image/svg+xml'}
const auth=(request:Request)=>{const cookie=request.headers.get('cookie')?.match(/(?:^|;\s*)dump_session=([^;]+)/)?.[1];const secret=process.env.DUMP_ACCESS_CODE;if(!cookie||!secret)return false;const a=Buffer.from(cookie),b=Buffer.from(createHmac('sha256',secret).update(`dump:${secret}`).digest('hex'));return a.length===b.length&&timingSafeEqual(a,b)}
export const dynamic='force-dynamic'
export async function GET(request:Request){if(!auth(request))return NextResponse.json({error:'UNAUTHORIZED'},{status:401});try{const r=await client.send(new ListObjectsV2Command({Bucket:process.env.R2_BUCKET_NAME!}));const files=(r.Contents||[]).map(o=>{const key=o.Key!,name=key.split('/').pop()||key,ext=name.includes('.')?name.split('.').pop()!.toLowerCase():'';return{key,name,size:o.Size||0,lastModified:o.LastModified,type:imageExtensions[ext]||'application/octet-stream',url:`/api/file?key=${encodeURIComponent(key)}`}});files.sort((a,b)=>new Date(b.lastModified||0).getTime()-new Date(a.lastModified||0).getTime());return NextResponse.json(files)}catch{return NextResponse.json({error:'Could not list files'},{status:500})}}
export async function DELETE(request:Request){if(!auth(request))return NextResponse.json({error:'UNAUTHORIZED'},{status:401});try{const{key}=await request.json();if(!key||typeof key!=='string')return NextResponse.json({error:'File key is required'},{status:400});await client.send(new DeleteObjectCommand({Bucket:process.env.R2_BUCKET_NAME!,Key:key}));return NextResponse.json({success:true,key})}catch{return NextResponse.json({error:'Could not delete file'},{status:500})}}
