'use client'

import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from 'react'
import styles from './page.module.css'

const API = '/api'
type Item = { key: string; name: string; size?: number; lastModified?: string; url: string; type?: string }
type Upload = { id: string; name: string; progress: number; state: 'uploading' | 'done' | 'error' }
const formatBytes = (bytes = 0) => { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const i = Math.min(Math.floor(Math.log(bytes)/Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** i).toFixed(i ? 1 : 0)} ${units[i]}` }
const fileName = (key: string) => key.split('/').pop() || key
const isImage = (item: Item) => item.type?.startsWith('image/') || /\.(jpe?g|png|gif|webp|avif|heic|heif|bmp|svg)$/i.test(item.key)
const isVideo = (item: Item) => item.type?.startsWith('video/') || /\.(mp4|webm|mov|m4v|avi)$/i.test(item.key)

export default function Home() {
 const inputRef = useRef<HTMLInputElement>(null)
 const [files,setFiles] = useState<Item[]>([]); const [uploads,setUploads] = useState<Upload[]>([]); const [dragging,setDragging] = useState(false); const [loading,setLoading] = useState(true); const [query,setQuery] = useState(''); const [sort,setSort] = useState('newest'); const [selected,setSelected] = useState<Item | null>(null)
 const loadFiles = useCallback(async()=>{ try { const r=await fetch(`${API}/files`,{cache:'no-store'}); if(!r.ok) throw new Error(); setFiles(await r.json()) } catch {} finally { setLoading(false) } },[])
 useEffect(()=>{loadFiles();const t=setInterval(loadFiles,4000);return()=>clearInterval(t)},[loadFiles])
 const upload = async(file:File)=>{const id=`${Date.now()}-${Math.random()}`;setUploads(u=>[...u,{id,name:file.name,progress:0,state:'uploading'}]);try{const r=await fetch(`${API}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size})});if(!r.ok)throw new Error();const{url}=await r.json();await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);if(file.type)x.setRequestHeader('Content-Type',file.type);x.upload.onprogress=e=>e.lengthComputable&&setUploads(u=>u.map(a=>a.id===id?{...a,progress:Math.round(e.loaded/e.total*100)}:a));x.onload=()=>x.status>=200&&x.status<300?resolve():reject();x.onerror=()=>reject();x.send(file)});setUploads(u=>u.map(a=>a.id===id?{...a,progress:100,state:'done'}:a));await loadFiles()}catch{setUploads(u=>u.map(a=>a.id===id?{...a,state:'error'}:a))}}
 const acceptFiles=(incoming:FileList|File[])=>Array.from(incoming).forEach(upload)
 const onChange=(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files)acceptFiles(e.target.files);e.target.value=''}
 const onDrop=(e:DragEvent)=>{e.preventDefault();setDragging(false);acceptFiles(e.dataTransfer.files)}
 useEffect(()=>{const paste=(e:ClipboardEvent)=>{const f=Array.from(e.clipboardData?.files||[]).filter(a=>a.type.startsWith('image/'));if(f.length)acceptFiles(f)};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste)},[])
 const visible = [...files].filter(f=>fileName(f.key).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='size'?(b.size||0)-(a.size||0):sort==='oldest'?new Date(a.lastModified||0).getTime()-new Date(b.lastModified||0).getTime():new Date(b.lastModified||0).getTime()-new Date(a.lastModified||0).getTime())
 const download = (f:Item)=>{const a=document.createElement('a');a.href=f.url;a.download=f.name;a.click()}
 const downloadAll = ()=>visible.forEach((f,i)=>setTimeout(()=>download(f),i*100))
 const keyHandler=(e:React.KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if((e.key==='ArrowRight'||e.key==='ArrowLeft')&&selected){const i=visible.findIndex(f=>f.key===selected.key);const n=e.key==='ArrowRight'?i+1:i-1;if(visible[n])setSelected(visible[n])}}
 return <main className={styles.page}>
 <header className={styles.topbar}><div className={styles.logo}>DUMP<span>.</span></div><div className={styles.tag}>SHARED FILE DROP / NO LOGIN</div></header>
 <section className={styles.hero}><div><p className={styles.eyebrow}>EVERYONE&apos;S INVITED</p><h1>DROP.<br/>SHARE.<br/>DONE.</h1></div><p className={styles.intro}>A shared corner of the internet for throwing files at your friends.</p></section>
 <button className={`${styles.dropzone} ${dragging?styles.dragging:''}`} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop}><span className={styles.plus}>+</span><strong>{dragging?'LET GO.':'DROP FILES HERE'}</strong><span>or click to browse · paste images with ⌘V / Ctrl+V</span><input ref={inputRef} type="file" multiple hidden onChange={onChange}/></button>
 {uploads.length>0&&<section className={styles.uploads}><div className={styles.sectionHead}><h2>UPLOADING</h2><button onClick={()=>setUploads([])}>CLEAR</button></div>{uploads.map(u=><div className={styles.upload} key={u.id}><span>{u.name}</span><div className={styles.bar}><i style={{width:`${u.progress}%`}}/></div><b>{u.state==='error'?'ERROR':`${u.progress}%`}</b></div>)}</section>}
 <section className={styles.library}><div className={styles.sectionHead}><h2>{loading?'LOADING…':`${visible.length} / ${files.length} FILE${files.length===1?'':'S'}`}</h2><div className={styles.controls}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH FILES..." aria-label="Search files"/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort files"><option value="newest">NEWEST</option><option value="oldest">OLDEST</option><option value="name">NAME</option><option value="size">SIZE</option></select><button disabled={!visible.length} onClick={downloadAll}>DOWNLOAD ALL ↓</button></div></div>
 {visible.length?<div className={styles.grid}>{visible.map(item=><article className={styles.card} key={item.key} onClick={()=>isImage(item)?setSelected(item):download(item)}><div className={styles.preview}>{isImage(item)?<img src={item.url} alt="" loading="lazy"/>:isVideo(item)?<video src={item.url} muted playsInline preload="metadata"/>:<span className={styles.filetype}>{(item.name.split('.').pop()||'FILE').toUpperCase()}</span>}</div><div className={styles.meta}><strong title={item.name}>{item.name}</strong><span>{formatBytes(item.size)}</span></div><button className={styles.download} onClick={e=>{e.stopPropagation();download(item)}}>DOWNLOAD ↓</button></article>)}</div>:<div className={styles.empty}>{files.length?'NO FILES MATCH.':'NOTHING HERE YET.'}<br/><small>{files.length?'TRY A DIFFERENT SEARCH.':'BE THE FIRST TO DUMP SOMETHING.'}</small></div>}</section>
 <footer className={styles.footer}><span>DUMP / PHASE 01</span><span>FILES LIVE UNTIL SOMEONE REMOVES THEM.</span></footer>
 {selected&&<div className={styles.lightbox} tabIndex={0} autoFocus onKeyDown={keyHandler} onClick={()=>setSelected(null)}><button className={styles.close} onClick={()=>setSelected(null)}>×</button><button className={styles.prev} onClick={e=>{e.stopPropagation();const i=visible.findIndex(f=>f.key===selected.key);if(visible[i-1])setSelected(visible[i-1])}}>←</button><div className={styles.lightboxInner} onClick={e=>e.stopPropagation()}><img src={selected.url} alt={selected.name}/><div><strong>{selected.name}</strong><button onClick={()=>download(selected)}>DOWNLOAD ↓</button></div></div><button className={styles.next} onClick={e=>{e.stopPropagation();const i=visible.findIndex(f=>f.key===selected.key);if(visible[i+1])setSelected(visible[i+1])}}>→</button></div>}
 </main>
}
