'use client'

import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from 'react'
import styles from './page.module.css'

const API = '/api'
type Item = { key: string; size?: number; lastModified?: string; url?: string; type?: string }
type Upload = { id: string; name: string; progress: number; state: 'uploading' | 'done' | 'error' }
const formatBytes = (bytes = 0) => { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const i = Math.min(Math.floor(Math.log(bytes)/Math.log(1024)), units.length-1); return `${(bytes/1024**i).toFixed(i ? 1 : 0)} ${units[i]}` }
const fileName = (key: string) => key.split('/').pop() || key
const isImage = (item: Item) => item.type?.startsWith('image/') || /\.(jpe?g|png|gif|webp|avif|heic)$/i.test(item.key)

export default function Home() {
 const inputRef=useRef<HTMLInputElement>(null); const [files,setFiles]=useState<Item[]>([]); const [uploads,setUploads]=useState<Upload[]>([]); const [dragging,setDragging]=useState(false); const [loading,setLoading]=useState(true)
 const loadFiles=useCallback(async()=>{try{const r=await fetch(`${API}/files`,{cache:'no-store'});if(!r.ok)throw new Error();setFiles(await r.json())}catch{}finally{setLoading(false)}},[])
 useEffect(()=>{loadFiles();const t=setInterval(loadFiles,4000);return()=>clearInterval(t)},[loadFiles])
 const upload=async(file:File)=>{const id=`${Date.now()}-${Math.random()}`;setUploads(u=>[...u,{id,name:file.name,progress:0,state:'uploading'}]);try{const r=await fetch(`${API}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size})});if(!r.ok)throw new Error();const{url}=await r.json();await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);if(file.type)x.setRequestHeader('Content-Type',file.type);x.upload.onprogress=e=>e.lengthComputable&&setUploads(u=>u.map(a=>a.id===id?{...a,progress:Math.round(e.loaded/e.total*100)}:a));x.onload=()=>x.status>=200&&x.status<300?resolve():reject();x.onerror=()=>reject();x.send(file)});setUploads(u=>u.map(a=>a.id===id?{...a,progress:100,state:'done'}:a));await loadFiles()}catch{setUploads(u=>u.map(a=>a.id===id?{...a,state:'error'}:a))}}
 const acceptFiles=(incoming:FileList|File[])=>Array.from(incoming).forEach(upload)
 const onChange=(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files)acceptFiles(e.target.files);e.target.value=''}
 const onDrop=(e:DragEvent)=>{e.preventDefault();setDragging(false);acceptFiles(e.dataTransfer.files)}
 useEffect(()=>{const paste=(e:ClipboardEvent)=>{const f=Array.from(e.clipboardData?.files||[]).filter(a=>a.type.startsWith('image/'));if(f.length)acceptFiles(f)};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste)})
 const downloadAll=()=>files.forEach((f,i)=>f.url&&setTimeout(()=>window.open(f.url,'_blank'),i*150))
 return <main className={styles.page}><header className={styles.topbar}><div className={styles.logo}>DUMP<span>.</span></div><div className={styles.tag}>SHARED FILE DROP / NO LOGIN</div></header><section className={styles.hero}><div><p className={styles.eyebrow}>EVERYONE&apos;S INVITED</p><h1>DROP.<br/>SHARE.<br/>DONE.</h1></div><p className={styles.intro}>A shared corner of the internet for throwing files at your friends.</p></section><button className={`${styles.dropzone} ${dragging?styles.dragging:''}`} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop}><span className={styles.plus}>+</span><strong>{dragging?'LET GO.':'DROP FILES HERE'}</strong><span>or click to browse · paste images with ⌘V / Ctrl+V</span><input ref={inputRef} type="file" multiple hidden onChange={onChange}/></button>{uploads.length>0&&<section className={styles.uploads}><div className={styles.sectionHead}><h2>UPLOADING</h2><button onClick={()=>setUploads([])}>CLEAR</button></div>{uploads.map(u=><div className={styles.upload} key={u.id}><span>{u.name}</span><div className={styles.bar}><i style={{width:`${u.progress}%`}}/></div><b>{u.state==='error'?'ERROR':`${u.progress}%`}</b></div>)}</section>}<section className={styles.library}><div className={styles.sectionHead}><h2>{loading?'LOADING…':`${files.length} FILE${files.length===1?'':'S'}`}</h2><button disabled={!files.length} onClick={downloadAll}>DOWNLOAD ALL ↓</button></div>{files.length?<div className={styles.grid}>{files.map(item=><a className={styles.card} key={item.key} href={item.url||'#'} target="_blank" rel="noreferrer"><div className={styles.preview}>{isImage(item)&&item.url?<img src={item.url} alt="" loading="lazy"/>:<span className={styles.filetype}>FILE</span>}</div><div className={styles.meta}><strong>{fileName(item.key)}</strong><span>{formatBytes(item.size)}</span></div></a>)}</div>:<div className={styles.empty}>NOTHING HERE YET.<br/><small>BE THE FIRST TO DUMP SOMETHING.</small></div>}</section><footer><span>DUMP / PHASE 01</span><span>FILES LIVE UNTIL SOMEONE REMOVES THEM.</span></footer></main>
}
